name: Build and Deploy Server
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t antxoneguigurenperez/ci-cd-server .
      - name: Publish Image to DockerHub
        run: docker push antxoneguigurenperez/ci-cd-server:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image fom DockerHub
        run: docker pull antxoneguigurenperez/ci-cd-server:latest
      - name: Delete Old Container
        run: docker rm -f ci-cd-server-container
      - name: Run Docker Container
        run: docker run -d -p 3300:3300 --name ci-cd-server-container antxoneguigurenperez/ci-cd-server
